---
- name: Install MySQL
  ansible.builtin.apt:
    name:
      - mysql-server
      - python3-pymysql
    state: latest
    update_cache: yes

- name: Ensure MySQL is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Deploy MySQL config
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /etc/mysql/mysql.conf.d/mysqld.cnf
  notify: Restart mysql

- name: Set root password
  community.mysql.mysql_user:
    name: root
    host: localhost
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    
- name: Create database
  community.mysql.mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    host: "%"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"